from pathlib import Path
from pdfwordsearch.scan.pdf_scan import pdf_to_dict

current_dir = Path(__file__).parent

lovely_path = current_dir.joinpath("../resources/lovely.pdf")


def test_pdf_scan():
    with open(lovely_path, "rb") as pdf:
        actual = pdf_to_dict(pdf)
        assert actual == {
            0: "What a lovely, \n"
            " \n"
            "delightful \n"
            "adj.#superb#groovy \n"
            "charming \n"
            "adj.#superb#groovy \n"
            "attractive \n"
            "adj.#beautiful#superb \n"
            "gorgeous \n"
            "adj.#beautiful \n"
            "nice \n"
            "adj.#appearance#look \n"
            "cute \n"
            "adj.#feature \n"
            "appealing \n"
            "adj.#excellent#super \n"
            "wonderful \n"
            "adj.#appearance \n"
            "fine \n"
            "adj.#excellent#great \n"
            "marvelous \n"
            "adj.#superb#groovy \n"
            "pretty \n"
            "adj.#look \n"
            "exquisite \n"
            "adj.#beautiful \n",
            1: "ravishing \n"
            "adj.#excellent#great \n"
            "great \n"
            "adj.#job#wonderful \n"
            "good \n"
            "adj.#superb#groovy \n"
            "handsome \n"
            "adj.#beautiful#superb \n"
            "sweet \n"
            "adj.#appearance \n"
            "good-looking \n"
            "adj.#look#beautiful \n"
            "pleasing \n"
            "adj.#super#great \n"
            "stunning \n"
            "adj.#beautiful \n"
            "alluring \n"
            "adj.#charm#marvelous \n"
            "fair \n"
            "adj.#marvelous#look \n"
            "enchanting \n"
            "adj.#great#charm \n"
            "adorable \n"
            "adj.#excellent#great \n"
            "pleasant \n"
            "adj.#appearance#great \n",
            2: "splendid \n"
            "adj.#excellent#great \n"
            "magnificent \n"
            "adj.#excellent#great \n"
            "elegant \n"
            "adj.#great#superb \n"
            "engaging \n"
            "adj.#appearance \n"
            "fascinating \n"
            "adj.#marvelous#superb \n"
            "excellent \n"
            "adj.#marvelous \n"
            "divine \n"
            "adj.#marvelous \n"
            "comely \n"
            "adj.#excellent#great \n"
            "beauteous \n"
            "adj.#marvelous#look \n"
            "fetching \n"
            "adj.#appearance \n"
            "grand \n"
            "adj.#marvelous \n"
            "sightly \n"
            "adj.#marvelous#beauty \n"
            "enjoyable \n"
            "adj.#appearance \n",
            3: "captivating \n"
            "adj.#charm#look \n"
            "agreeable \n"
            "adj.#excellent#superb \n"
            "beauty \n"
            "noun#superb#groovy \n"
            "bonny \n"
            "adj.#excellent#superb \n"
            "fabulous \n"
            "adj.#superb#groovy \n"
            "winning \n"
            "adj.#superb#groovy \n"
            "heavenly \n"
            "adj.#job#pleasant \n"
            "terrific \n"
            "adj.#superb#groovy \n"
            "fantastic \n"
            "adj.#superb#groovy \n"
            "winsome \n"
            "adj.#appearance#taste \n"
            "endearing \n"
            "adj.#charm#charming \n"
            "amazing \n"
            "adj.#appearance \n"
            "bewitching \n"
            "adj.#charm#appearance \n",
            4: "lovable \n"
            "adj.#appearance \n"
            "superb \n"
            "adj.#beautiful#job \n"
            "graceful \n"
            "adj.#appearance \n"
            "foxy \n"
            "adj.#marvelous \n"
            "glorious \n"
            "adj.#superb#groovy \n"
            "awesome \n"
            "adj.#beautiful#superb \n"
            "statuesque \n"
            "adj.#superb#groovy \n"
            "picturesque \n"
            "adj.#superb#groovy \n"
            "enticing \n"
            "adj.#marvelous \n"
            "delicious \n"
            "adj.#appearance \n"
            "pleasurable \n"
            "adj.#groovy#superb \n"
            "dazzling \n"
            "adj.#superb#groovy \n"
            "pulchritudinous \n"
            "adj.#superb#groovy \n",
            5: "admirable \n"
            "adj.#marvelous#charm \n"
            "glamorous \n"
            "adj.#charm#appearance \n"
            "gratifying \n"
            "adj.#excellent#superb \n"
            "darling \n"
            "adj.#pleasant \n"
            "sexy \n"
            "adj.#marvelous \n"
            "sublime \n"
            "adj.#beautiful \n"
            "prepossessing \n"
            "adj.#appearance \n"
            "scenic \n"
            "adj.#superb#groovy \n"
            "knockout \n"
            "adj.noun#look#beautiful \n"
            "personable \n"
            "adj.#beauty#smell \n"
            "delectable \n"
            "adj.#appearance \n"
            "satisfying \n"
            "adj.#superb#groovy \n"
            "aesthetic \n"
            "adj.#superb#groovy \n",
            6: "well-formed \n"
            "adj.#marvelous \n"
            "stunner \n"
            "noun#beauty#beautiful \n"
            "hot \n"
            "adj.#marvelous#job \n"
            "congenial \n"
            "adj.#superb#groovy \n"
            "cool \n"
            "adj.#slang#appearance \n"
            "brilliant \n"
            "adj.#superb#groovy \n"
            "friendly \n"
            "adj.#endearing \n"
            "likable \n"
            "adj.#appearance \n"
            "amiable \n"
            "adj.#appearance#taste \n"
            "swell \n"
            "adj.#groovy#excellent \n"
            "sensational \n"
            "adj.#job#delight \n"
            "seductive \n"
            "adj.#appearance \n"
            "kind \n"
            "adj.#innocent \n",
            7: "inviting \n"
            "adj.#beauty#good \n"
            "marvellous \n"
            "adj.#pleasant#delight \n"
            "super \n"
            "adj.#delight#feeling \n"
            "dear \n"
            "adj.#gorgeous \n"
            "irresistible \n"
            "adj.#superb#groovy \n"
            "taking \n"
            "adj.#appearance#like \n"
            "person like me.  \n",
        }
